accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.user_registration, name="register"),
    path('profile/', views.edit_profile, name="edit_profile"),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from videos import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('videos/', include('videos.urls', namespace="videos")),
    path('<str:username>/', views.profile, name='profile'),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

videos/urls.py
from django.urls import path

from . import views

app_name = "videos"


urlpatterns = [
    path('video/<int:id>/', views.video, name='video'),
    path('add_video/', views.add_video, name='add_video'),
    path('comment/', views.comment, name='comment'),
    path('remove/', views.remove, name='remove'),
    path('edit_video/<int:id>/', views.edit_video, name='edit_video'),
    path('delete/<int:id>/', views.delete_video, name='delete_video'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import (BaseUserManager, AbstractBaseUser)


class CustomUserManager(BaseUserManager):
    def create_user(self, username, email, password=None):
        if not email:
            raise ValueError('The Email must be set')

        user = self.model(username=username,
                          email=self.normalize_email(email)
                          )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password=None):
        user = self.create_user(
                username, email, password=password
              )
        user.is_admin = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser):
    username = models.CharField(max_length=300, unique=True)
    email = models.EmailField(
                  max_length=255,
                  unique=True,
                  verbose_name='email address')
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser

User = get_user_model()


class CustomUserCreationForm(forms.ModelForm):
	
    username = forms.CharField(
                  label='Username',
                  max_length=100,
                  min_length=5,
                  widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(
                  widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(
                  label="Password",
                  max_length=100,
                  min_length=5,
                  widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(
                  label="Confirm Password",
                  max_length=100,
                  min_length=5,
                  widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
	    model = CustomUser
	    fields = ('username', 'email', 'password1', 'password2')
	 
	    
    def clean_email(self):
        email = self.cleaned_data['email']
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError('Email is already registered.')
        return email
	
	  
    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('Username is already in use.')
        return username
        
                
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Passwords do not match')
        return password2

        

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])

        if commit:
            user.save()
        return user
        


class ProfileForm(forms.ModelForm):

    username = forms.CharField(
                  label='Username',
                  max_length=100,
                  min_length=5,
                  widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(
                  widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'avatar', ]
        
        
        
    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            user = User.objects.exclude(pk=self.instance.pk).get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError('Username is already in use.')
        
        
    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            user = User.objects.exclude(pk=self.instance.pk).get(email=email)
        except User.DoesNotExist:
            return email
        raise forms.ValidationError('Email is already in use.')       

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import CustomUserCreationForm, ProfileForm


def login_user(request):
    if request.method == "POST":
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            redirect_url = request.GET.get('next', 'home')
            return redirect(redirect_url)
        else:
            messages.error(request, 'Bad email or password')
    return render(request, 'accounts/login.html', {})


def logout_user(request):
    logout(request)
    return redirect('accounts:login')


def user_registration(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Registration was successful',
                             extra_tags='alert alert-success alert-dismissible fade show'  # noqa: E501
                            )
            return redirect('home')
    else:
        form = CustomUserCreationForm()
    return render(request, 'accounts/register.html', {'form': form})


def edit_profile(request):
    form = ProfileForm(instance=request.user)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile was successfully updated ',
                             extra_tags='alert alert-success alert-dismissible fade show'  # noqa: E501
                            )
            return HttpResponseRedirect(reverse('profile', args=[str(request.user.username)]))  # noqa: E501

    return render(request, 'accounts/edit_profile.html', {'form': form})

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block content %}

 <div class="container">
    <div class="row">
      <div class="col-sm-6 offset-sm-3">
      
        <!-- <h2 class="mt-5 text-center">Edit Profile</h2> -->
        
        {% if messages %}
          {% for message in messages %}
          <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {{message}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
               <span aria-hidden="true">&times;</span>
             </button>
          </div>
          {% endfor %}
        {% endif %}
        
        <div class="card border-primary mt-5 mb-3">
          <div class="card-header">Edit Profile</div>
            <div class="card-body text-primary">
              <form action="{% url 'accounts:edit_profile' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                  <div class="form-group ">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {{ field }}
                  </div>
                {% endfor %}
                <input type="submit" value="Submit" class="btn btn-primary">
              </form>
            </div>
          </div>
        </div>      
        
        
      </div>
    </div>
  </div>
        
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  

<div class="container">

  <div class="row">
    <div class="mt-5 col-md-6 offset-md-3">
      {% if messages %}
        <ul class="messages">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
          {% endfor %}
        </ul>
      {% endif %}
      <div class="text-center mb-3" style = "width: 100%;">
        <img src="{% static 'img/i-tube.png' %}" alt="" width="180px" />
      </div>
      
      <div class="card border-primary mb-3">
        <div class="card-header">Sign In</div>
          <div class="card-body text-primary">
            <form action="" method="post">
              {% csrf_token %}
              
              <div class="form-group">
                <label for="email">Email</label>
                <input type="text" class="form-control" name="email" placeholder="Enter email">
              </div>
              <div class="form-group">
                <label for="password">Password</label>
                <input type="password" class="form-control" name="password" placeholder="Enter password">
              </div>
              <button type="submit" class="btn btn-primary">Sign In</button>
            </form>
        </div>
      </div>
      
      <p>Need an account? <a href="{% url 'accounts:register' %}">Register Here!</a></p>
    </div>
  </div>

</div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-sm-6 offset-sm-3">
        <p class="text-center mt-4" >Already have an account? <a href="{% url 'accounts:login' %}">Login Here!</a></p>
        
        <div class="card border-primary mb-3">
          <div class="card-header">Register</div>
            <div class="card-body text-primary">
              <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}
                  <div class="form-group">
                    {{ field.errors }}
                    {{ field.label_tag }}
                    {{ field }}
                  </div>
                {% endfor %}
                <input type="submit" value="Register" class="btn btn-primary">
              </form>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>

{% endblock %}