accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.user_registration, name="register"),
    path('profile/', views.edit_profile, name="edit_profile"),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from videos import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('videos/', include('videos.urls', namespace="videos")),
    path('<str:username>/', views.profile, name='profile'),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

videos/urls.py
from django.urls import path

from . import views

app_name = "videos"


urlpatterns = [
    path('video/<int:id>/', views.video, name='video'),
    path('add_video/', views.add_video, name='add_video'),
    path('comment/', views.comment, name='comment'),
    path('remove/', views.remove, name='remove'),
    path('edit_video/<int:id>/', views.edit_video, name='edit_video'),
    path('delete/<int:id>/', views.delete_video, name='delete_video'),
]

templates/includes/modal.html
<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div id="modal-content" class="modal-content">
    </div>
  </div>
</div>

templates/includes/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'img/i-tube-white.png' %}" alt="" width="120px"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <!-- <div class="navbar-nav">
      {% if request.user.is_authenticated %}
        <a class="nav-item nav-link active" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      {% endif %}
    </div> -->
    <div class="navbar-nav ml-auto">
      {% if request.user.is_authenticated %}
        <a class="nav-item nav-link active" href="{% url 'profile' user.username %}">Profile ({{user.username}}) </a>
        <a class="nav-item nav-link active" href="{% url 'accounts:logout' %}">Logout</a>

      {% else %}  
      <a class="nav-item nav-link active" href="{% url 'accounts:login' %}">Login</a>
      {% endif %}
    </div>
  </div>
</nav>

templates/includes/paginator.html
<div class="pagination">
  <span class="step-links">
     {% if videos.has_previous %}
         <a href="?page=1&{{params}}">&laquo; first</a>
         <a href="?page={{ videos.previous_page_number }}&{{params}}">previous</a>
     {% endif %}

     <span class="current">
        Page {{ videos.number }} of {{ videos.paginator.num_pages }}.
     </span>

     {% if videos.has_next %}
        <a href="?page={{ videos.next_page_number }}&{{params}}">next</a>
        <a href="?page={{ videos.paginator.num_pages }}&{{params}}">last &raquo;</a>
     {% endif %}
   </span>
</div>