accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.login_user, name="login"),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.user_registration, name="register"),
    path('profile/', views.edit_profile, name="edit_profile"),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from videos import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('videos/', include('videos.urls', namespace="videos")),
    path('<str:username>/', views.profile, name='profile'),
    path('accounts/', include('accounts.urls', namespace="accounts")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

videos/urls.py
from django.urls import path

from . import views

app_name = "videos"


urlpatterns = [
    path('video/<int:id>/', views.video, name='video'),
    path('add_video/', views.add_video, name='add_video'),
    path('comment/', views.comment, name='comment'),
    path('remove/', views.remove, name='remove'),
    path('edit_video/<int:id>/', views.edit_video, name='edit_video'),
    path('delete/<int:id>/', views.delete_video, name='delete_video'),
]

videos/models.py
from django.db import models
from django.conf import settings


class Video(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)  # noqa: E501
    date = models.DateTimeField(auto_now_add=True)
    post = models.TextField(max_length=255)
    video_file = models.FileField(upload_to='videos/', blank=True, null=True)
    parent = models.ForeignKey('Video', null=True, blank=True, on_delete=models.CASCADE)  # noqa: E501
    comments = models.IntegerField(default=0)

    def __str__(self):
        return self.post

    def get_comments(self):
        return Video.objects.filter(parent=self).order_by('-date')

    def calculate_comments(self):
        self.comments = Video.objects.filter(parent=self).count()
        self.save()
        return self.comments

    def comment(self, user, post):
        video_comment = Video(user=user, post=post, parent=self)
        video_comment.save()
        self.comments = Video.objects.filter(parent=self).count()
        self.save()
        return video_comment

videos/forms.py
from django import forms

from videos.models import Video


class VideoForm(forms.ModelForm):
    post = forms.CharField(
              label="",
              widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter video title here'}),  # noqa: E501
              max_length=255
                           )

    class Meta:
        model = Video
        fields = ['post', 'video_file']

    def clean_video_file(self):

        VIDEO_FILE_TYPES = ['mp4']

        uploaded_video = self.cleaned_data.get("video_file",  False)

        extension = str(uploaded_video).split('.')[-1]

        file_type = extension.lower()

        if not uploaded_video:
            raise forms.ValidationError("please upload a video")

        if file_type not in VIDEO_FILE_TYPES:
            raise forms.ValidationError("Upload an mp4 file")

        return uploaded_video

videos/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.contrib.auth import get_user_model
from videos.models import Video
from videos.forms import VideoForm


User = get_user_model()


# @login_required
def home(request):
    videos = Video.objects.filter(parent=None).order_by('?')
    paginator = Paginator(videos, 6)
    page = request.GET.get('page')
    all_videos = paginator.get_page(page)
    return render(request, "videos/home.html", {'videos': all_videos})


@login_required
def add_video(request):
    data = {}
    form = VideoForm()
    if request.method == "POST":
        form = VideoForm(request.POST, request.FILES)
        if form.is_valid():
            video = form.save(commit=False)
            video.user = request.user
            video.video_file = form.cleaned_data.get('video_file')
            video.post = form.cleaned_data.get('post')
            video.save()
            data['form_is_valid'] = True
            return JsonResponse(data)
        else:
            data['form_is_valid'] = False
            data['video_form'] = render_to_string("videos/video_form.html", {'form': form}, request=request)  # noqa: E501

    data['video_form'] = render_to_string("videos/video_form.html", {'form': form}, request=request)  # noqa: E501
    return JsonResponse(data)


@login_required
def edit_video(request, id):
    data = {}
    video = get_object_or_404(Video, pk=id)
    form_instance = VideoForm(instance=video)
    if request.method == "POST":
        form = VideoForm(request.POST, request.FILES, instance=video)
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            return JsonResponse(data)
        else:
            data['form_is_valid'] = False
            data['edited_video'] = render_to_string("videos/edit_video.html", {'form': form}, request=request)  # noqa: E501

    data['edit_video'] = render_to_string("videos/edit_video.html", {'form': form_instance}, request=request)  # noqa: E501
    return JsonResponse(data)


@login_required
def delete_video(request,id):    
    video = Video.objects.get(pk=id)
    if video.user == request.user:        
        video.delete()
   
    all_videos = Video.objects.filter(parent=None).filter(user=request.user)
    return render(request, 'videos/profile.html', {'page_user': request.user, 'all_videos': all_videos})    

    


# @login_required
def video(request, id):
    video = get_object_or_404(Video, id=id)
    side_videos = Video.objects.filter(parent=None).order_by('?').exclude(id=id)[:4]  # noqa: E501
    return render(request, 'videos/video.html', {'video': video, 'side_videos': side_videos})  # noqa: E501


@login_required
def comment(request):
    data = {}
    if request.method == 'POST':
        video_id = request.POST['video_id']
        video = Video.objects.get(pk=video_id)
        post = request.POST['post']
        post = post.strip()
        if len(post) > 0:
            user = request.user
            video.comment(user=user, post=post)
            data['partial_video_comments'] = render_to_string('videos/partial_video_comments.html', {'video': video}, request=request)  # noqa: E501
            data['comment_count'] = video.calculate_comments()
            return JsonResponse(data)
        else:
            return JsonResponse(data)


@login_required
def profile(request, username):
    page_user = get_object_or_404(User, username=username)
    all_videos = Video.objects.filter(parent=None).filter(user=page_user)
    return render(request, 'videos/profile.html', {'page_user': page_user, 'all_videos': all_videos})  # noqa: E501


@login_required
def remove(request):
    data = {}
    comment_id = request.POST.get('comment_id')
    comment = Video.objects.get(pk=comment_id)
    if comment.user == request.user:
        parent = comment.parent
        comment.delete()
        data['comment_count'] = parent.calculate_comments()

    data['partial_video_comments'] = render_to_string('videos/partial_video_comments.html', {'video': parent}, request=request)  # noqa: E501
    return JsonResponse(data)

videos/templates/videos/edit_video.html
<div class="modal-header">
   <h5 class="modal-title" id="staticBackdropLabel"> Edit video</h5>
   <button type="button" class="close" data-dismiss="modal" aria-label="Close">
     <span aria-hidden="true">&times;</span>
   </button>
</div>

<div class="modal-body">
          
 <form action="" method="post" enctype='multipart/form-data'>
     {% csrf_token %}
     {% for field in form %}
     <div class="form-group">
       {{ field.errors }}
       {{ field.label_tag }}
       {{ field }}
     </div>
       {% endfor %}   
 </form>

</div>
           
<div class="modal-footer">
 <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
 <button type="button" id="submit_edited_video" data-id="{{form.instance.pk}}" class="btn btn-primary">Submit</button>
</div>

videos/templates/videos/home.html
{% extends 'base.html' %}

{% load staticfiles %}

{% load humanize %}

{% block title %} I-Tube {% endblock %}

{% block content %}
<div class="container">

  {% csrf_token %}
  
  <div class="row">
   <div class=" mt-3  offset-sm-2 col-md-8">
     
      {% if messages %}
        {% for message in messages %}
          <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {{message}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        {% endfor %}
       {% endif %}
   
     {% if not videos %}    
     
       <h4 class="mt-5 text-center"> Welcome to I-Tube ! There are no videos currently, go to your profile and upload atleast 10 videos </h4>
      
     {% endif %}
    </div>
  
  </div>
  
  
  <div class="mt-5 row">
     {% for video in videos %}
        <div class="col-md-4 mb-3">

          <div class="card border-primary mb-3"> 
            <div class="card-body">           
              <a href="{% url 'videos:video' video.id %}">
              
                <video id="vid" width="100%" height="200px;">
                  <source src="{{ video.video_file.url}}" type="video/mp4">
                </video> 
                
              </a>
            </div>  
            <div class="card-footer bg-light">
              <h5 class="card-title">{{video.post|truncatechars:42}} </h5>
              <p class="card-text">{{video.date|naturaltime }}</p>
              
            </div>
          </div>
        
          <!-- <div class="card">
            
            <div class="card-header">
              <small class="ml-1">{{video.date|naturaltime }}</small>
            </div>
           
            <div class="card-body">
              <a href="{% url 'videos:video' video.id %}">
             
                <video id="vid" width="100%" height="200px;">
                  <source src="{{ video.video_file.url}}" type="video/mp4">
                </video> 
                
              </a>
            </div>
            
            <div class="card-footer"> 
              {{video.post|truncatechars:42}}  
              
            </div>
            
          </div> -->
          
        </div> 
        {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
     {% endfor %}
   </div>
   
   {% if  videos %} 
   <div class="row">
      <div class="col-md-12">
        {% include 'includes/paginator.html' with videos=videos %}
      </div>
   </div>
   {% endif %}
   
   
</div>

{% endblock %}

videos/templates/videos/partial_video_comments.html
{% load humanize %}

{% load staticfiles %}

{% for comment in video.get_comments %}     
   <li class="my-3" >
     {% if comment.user.avatar %}
         <a href="{% url 'profile' comment.user.username %}">
            <img  src="{{comment.user.avatar.url}}" alt="profile_pic" class="comment-profile rounded-circle float-left">
         </a>
       {% else %}
          
         <a href="{% url 'profile' comment.user.username %}">
            <img  src="{% static 'img/user.png' %}" class="comment-profile rounded-circle float-left" alt="profile_pic" />
         </a>
     {% endif %}
    
     <div class="ml-4">
        <div class="ml-4">
          <a href="{% url 'profile' comment.user.username %}">
            {{comment.user.username}}
          </a>
          
          <small class="ml-1">{{comment.date|naturaltime }}</small>
          
          {% if comment.user.username == user.username %}
            <i data-id="{{ comment.pk }}" id="remove" class="float-right  fa fa-close" ></i>
          {% endif %}
          
        </div>
        <div  class="ml-4"> {{ comment.post }}  </div> 
     </div>
   </li>
   {% empty %}
   <li class="empty"> Be the first one to comment </li>
{% endfor %}

videos/templates/videos/profile.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %} {{page_user.username}} {% endblock %}

 

{% block content %}
<div class="container">

  {% csrf_token %}
  <div class="mt-5 row">
      <div class="col-sm-10 offset-sm-1">
      
        {% if messages %}
          {% for message in messages %}
          <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {{message}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
               <span aria-hidden="true">&times;</span>
             </button>
          </div>
          {% endfor %}
        {% endif %}
      
        {% if page_user.avatar %}
           <a href="{% url 'profile' page_user.username %}">
             <img  src="{{page_user.avatar.url}}" alt="profile_pic" class="user-profile-pic mr-4 rounded-circle float-left">
           </a>
          {% else %}
           <a href="{% url 'profile' page_user.username %}">
             <img  src="{% static 'img/user.png' %}" class="user-profile-pic mr-4 rounded-circle float-left" alt="profile_pic" />
           </a>
        {% endif %}
      
       
        {% if user.id == page_user.id %}
          <button  id="upload" type="button" class="float-right btn btn-outline-primary">Upload video</button>
        {% endif %}
       
        <div class="ml-5">
           <div class="ml-4 my-1">
             <a class="text-dark" href="{% url 'profile' page_user.username %}">
              {{page_user.username}}
             </a>
           </div>
         
           <div  class="ml-4">
             {% if user.id == page_user.id %}
              <a href="{% url 'accounts:edit_profile' %}"  role="button" class="btn btn-outline-primary btn-sm">Edit profile</a>
             {% endif %}
           </div> 
        </div>
      </div>
      
   </div> 
  
    <h2 class="mt-5 mb-3"> Videos </h2>
    
    {% if not all_videos %}
       {% if user.id == page_user.id %}
          <h4 class="mt-5 text-center"> There are no videos currently, upload atleast 10 videos using the upload button above </h4>
       {% endif %}
    {% endif %}
  
    <div class=" row">
     {% for video in all_videos %}
        <div class="col-md-4 mb-3">
          <div class="card">
            <div class="card-body">
            
              <a href="{% url 'videos:video' video.id %}">
                <video id="vid" width="100%" height="200px;">
                  <source src="{{ video.video_file.url}}" type="video/mp4">
                </video> 
              </a>
              
            </div>
            
            <div class="card-footer bg-light"> 
              {{video.post}}  
            </div>
            
          </div>
          
        </div>
        {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
     {% endfor %}
   </div>
  
</div> 

{% endblock %}

videos/templates/videos/video.html
{% extends 'base.html' %}

{% load staticfiles %}

{% load humanize %}

{% block title %}  {{video.post|truncatechars:42}} - I-Tube  {% endblock %}



{% block content %}
<div class="container">
  
  {% csrf_token %}
   
  <div class="row"> 
  
    <div class="mt-5 col-md-8"> 
    
       <div class="card ">
       
         <div class="card-header text-white bg-secondary">
           <small class="mr-1">uploaded : </small> <small class="ml-1">{{video.date|naturaltime }}</small>
         </div>
        
         <div class="card-body">
         
            <video  width="100%" height="100%" controls>
             <source src="{{ video.video_file.url }}" type="video/mp4">
            </video> 
         
         </div>
         
         <div class="card-footer text-white bg-secondary"> 
              {{video.post}} 
         </div>
         
       </div>
     
       
       <div class="my-4 clearfix">
       
          {% if video.user.avatar %}
           <a href="{% url 'profile' video.user.username %}">
             <img  src="{{video.user.avatar.url}}" alt="profile_pic" class="video-owner-pic rounded-circle float-left">
           </a>
          {% else %}
           <a href="{% url 'profile' video.user.username %}">
             <img  src="{% static 'img/user.png' %}" class="video-owner-pic rounded-circle float-left" alt="profile_pic" />
           </a>
          {% endif %}
         
         
         {% if video.user.username == user.username %}
         <div class="float-right">
            <button id="edit" data-id="{{video.id}}" type="button" class=" btn btn-secondary">Edit</button>
            <a href="{% url 'videos:delete_video' video.id %}">  
              <button id="delete" type="button" class=" btn btn-danger">Delete</button>
            </a>
          </div>
           
         {% endif %}
         
         <div class="ml-5">
        
           <div class="ml-4 my-1">
             <a href="{% url 'profile' video.user.username %}">
               {{video.user.username}}
             </a>
           </div>
           
         </div>
         
       </div> 
      
       <span class="comments">Comments</span> (<span id="commentcount">{{video.calculate_comments}}</span>)
       
       <div class="my-4">
         <form id="comment" role="form" method="post" action="#" onsubmit="return false">
           <input type="hidden" name="video_id" value="{{video.id}}">
           <input id="usercomment"  type="text" class="form-control input-sm" placeholder=" Write a comment... " name="post" maxlength="255">
         </form>
       </div>
      
       <ul id="commentcontainer" class="mb-4 clearfix">
         {% include 'videos/partial_video_comments.html' %}
       </ul>
     
     
    </div>  
   
   
    <div class="mt-5 col-md-4">
     {% for video in side_videos %}
      
       <div class="mb-3 card">
       
         <div class="card-header text-white bg-secondary">
            <small class="ml-1">{{video.date|naturaltime }}</small>
         </div>
       
        <div class="card-body">
          <a href="{% url 'videos:video' video.id %}">
          
            <video id="vid" width="100%" height="200px;">
             <source src="{{ video.video_file.url }}" type="video/mp4">
            </video> 
           
          </a>
          
        </div>
        
        <div class="card-footer text-white bg-secondary"> 
          {{video.post|truncatechars:42}}  
              
        </div>
      
       </div>
     
     {% endfor %}
   </div>
     
 </div> 
  
   
</div> 

{% endblock %}

videos/templates/videos/video_form.html
<div class="modal-header">
   <h5 class="modal-title" id="staticBackdropLabel"> Add video</h5>
   <button type="button" class="close" data-dismiss="modal" aria-label="Close">
     <span aria-hidden="true">&times;</span>
   </button>
</div>

<div class="modal-body">
          
  <form action="" method="post" enctype='multipart/form-data'>
     {% csrf_token %}
     {% for field in form %}
     <div class="form-group">
       {{ field.errors }}
       {{ field.label_tag }}
       {{ field }}
     </div>
       {% endfor %}   
  </form>

</div>
          
<div class="modal-footer">
 <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
 <button type="button" id="video_submit" class="btn btn-primary">Submit</button>
</div>